### ISSUE TITLE
CI/CD along with Bash-Script

### ISSUE THREAD

**Issue by rajavishah** [bilayer-containers/bilayers#16]
### Discussed in https://github.com/orgs/bilayer-containers/discussions/15

<div type='discussions-op-text'>

<sup>Originally posted by **rajavishah** June 24, 2024</sup>
As discussed with @gnodar01, we are developing CI/CD pipeline which takes `algorithm-names` and `interface-names` from a bash script. Eventually, the script would run for `m*n` times. (m = number of algorithms, n = number of interfaces). 

Currently, I have developed it as - Github Actions would have one `step` where it runs the whole bash script : https://github.com/bilayer-containers/bilayers/blob/2fbe84bd354fb138a2127f279b838e3a9a5822d4/.github/workflows/docker-build.yml#L32

But we can also think as bash script would only contain the names of the algorithm and interfaces whilst every `nox session` will be run in `CI/CD workflow`

Any suggestions @gnodar01 , @bethac07 ?
</div>

**Comment by bethac07** [comment]
Yeah, we'll want to be thoughtful about when we trigger and how often - this will probably need some thought!

**Comment by gnodar01** [comment]
> But we can also think as bash script would only contain the names of the algorithm and interfaces whilst every nox session will be run in CI/CD workflow

This is probably preferred. Gives us a clean environment per build.
