### ISSUE TITLE
JupyterNB Interface - Single Cell for Variable Input

### ISSUE THREAD

**Issue by rajavishah** [bilayer-containers/bilayers#27]
### Discussed in https://github.com/orgs/bilayer-containers/discussions/24

<div type='discussions-op-text'>

<sup>Originally posted by **rajavishah** July 24, 2024</sup>
According to the discussion on Slack, Instead of having a bunch of cells or widgets for input parameters in Jupyter Notebook Interface, we would want to go with single cell. The approach should be to have a single cell that indicates the variables to be set, followed by a `!shell command` to execute. This would simplify the interface and avoid the need for multiple cells or widgets, especially when dealing with a large number of parameters like cellpose has</div>

**Comment by bethac07** [comment]
Update on this - we definitely now are happy with widgets now that we've gotten them compact-ified, the major thing was just not to create too-overwhelming of an interface. Hooray!
