### ISSUE TITLE
Enhance Bug Reporting(Error display) Feature

### ISSUE THREAD

**Issue by rajavishah** [bilayer-containers/bilayers#33]
Currently, our error display is functional and prompts users to take a screenshot and paste it under the "bilayers" issues section on GitHub. However, I came across `Gradio’s documentation` includes a bug reporting feature that directly opens GitHub issues with a pre-filled form, providing a better user experience. 

We could implement a similar interface that automates this process. [Here](https://github.com/gradio-app/gradio/issues/new?assignees=&labels=bug&projects=&template=bug_report_template.yml) is the link to their bug reporting page and how they [implemented](https://github.com/gradio-app/gradio/blob/main/.github/ISSUE_TEMPLATE/bug_report_template.yml) it via ISSUE TEMPLATES

<img width="1737" alt="Screenshot 2024-08-15 at 8 17 24 AM" src="https://github.com/user-attachments/assets/ec767492-baf1-49ba-9a43-d1e034a0df5c">

**Comment by bethac07** [comment]
Issue templates are a great idea! We have some in CellProfiler as well. Feel free to pull inspiration from wherever!
