### ISSUE TITLE
Jupyter Notebook is unable to display output files on the interface

### ISSUE THREAD

**Issue by rajavishah** [bilayer-containers/bilayers#34]
Currently, our Jupyter notebook supports both options: running with and without volume mounting. When volume mounting is used, the output files are generated in the same directory as the `input_images`, which allows users to access the output files via Docker Desktop by navigating to the volume-mounted directory.

However, we're facing an issue displaying the output files. The generation of Accordions is handled by the [`jupyter_template.py.j2`](https://github.com/bilayer-containers/bilayers/blob/v0.1_template_and_folder/src/Build/parse/jupyter_template.py.j2#L93) file, while the execution of shell commands via `!{shell command}` is managed by the [`generate.py`](https://github.com/bilayer-containers/bilayers/blob/v0.1_template_and_folder/src/Build/parse/generate.py#L102) file. The problem arises because `generate.py` doesn't have access to the specific flag that contains the folder path argument. It simply runs the `!{shell command}` without knowing the exact folder name. 

To properly display the output files, we need to access the folder name and iterate over the files in that directory.

In Gradio, we are doing like [this!](https://github.com/bilayer-containers/bilayers/blob/v0.1_template_and_folder/src/Build/parse/gradio_template.py.j2#L130-L143)

**Comment by bethac07** [comment]
Let's discuss this in checkin, but I don't get why we'd do it without volume mounting. I think this is a place we can enforce consistency, but lmk if I've missed a use case.

**Comment by rajavishah** [comment]
Now since, it's Volume Mounted, users can directly go and check via `docker-desktop --> Files` or in their `local-folders`

**Comment by rajavishah** [comment]
Seems resolved, hence closing this
