### ISSUE TITLE
Changes needed in config.yaml

### ISSUE THREAD

**Issue by rajavishah** [bilayer-containers/bilayers#36]
As per discussion, we would like to implement the following changes at the `config.yaml` level: 
 1. **Section Name Change**: - Rename the `inputs` section to `parameters`? (or maybe something else)
 2. **Output Section Updates**: - The `outputs` section should now include all the flags currently present in the `inputs` section that are missing, such as `cli_tag`, `optional`, and `section_id`.
 3. **New Output Directory Flags**: - We gonna introduce two new flags for the `outputs` section: - `output_dir_set` - `output_dir_get` - If `output_dir_set` is an empty string (`""`), it should default to the value provided by `output_dir_get`. 
 4. **Parameter Ordering**: - We need to introduce ordering for the parameters. - Both the `inputs` (in future `parameters`) and `outputs` sections should now have ordering, which will be considered when generating the `cli_command`. - The `outputs` section will have only one parameter to parse for building up `cli_command`: the folder where the output should be saved.
 5. **Positional Order**: - Positional ordering argument will only be passed if they are explicitly set to "yes." - One approach came to mind is to place all the cli_tags into a priority queue whilst parsing, and later when `cli_command` is constructed they are appended according to their priority. - If the positional argument does not affect the command structure, the current behavior of appending the command can continue. 

Plus, the current change to the code that - 
1. `gradio` only allows `non-volume mount`
2. `jupyter` only allows `volume mount` looks good to us?

P.S. - We already have code for both Volume Mount and Non Volume Mount for both the interface, we just need to uncomment that, if needed

**Comment by bethac07** [comment]
Thanks for writing all of this up!

A couple of nuances
- We probably need to be slightly more nuanced in how we determine if this is an `set` vs `get` situation for the `output_dir` - because it might be settable _in theory_ but the default location is `/.`, aka current directory. We might want to have a T/F flag on `output_dir_set`
- Parameter and positional ordering there are redundant unless I am misunderstanding what you have written. We can probably get a way with a config setting that's something like `cli_order = False` that then if set to an int we do in int ordering (and then maybe later, support negative ints to add some flags specifically as last)

**Comment by rajavishah** [comment]
> * Parameter and positional ordering there are redundant unless I am misunderstanding what you have written. We can probably get a way with a config setting that's something like `cli_order = False` that then if set to an int we do in int ordering (and then maybe later, support negative ints to add some flags specifically as last)

Yes, with `Positional Ordering` thing, I meant to somewhere define `cli_order` in the `config.yaml` level. But, this makes much more clear now. At the high level, we should put `cli_order` flag and it's type `Int` as of now

**Comment by rajavishah** [comment]
> * We probably need to be slightly more nuanced in how we determine if this is an `set` vs `get` situation for the `output_dir` - because it might be settable _in theory_ but the default location is `/.`, aka current directory. We might want to have a T/F flag on `output_dir_set`

Sorry, one more clarification question that we want to save `outputs` for both the `interfaces` via given `output_dir` thing, or this option we are only thinking for `jupyter`. I believe both, but correct me if I understood otherwise

**Comment by bethac07** [comment]
So, to be super clear on the ordering thing: here are two parameters pulled from the current cellpose config:

```
  - name: dir
    type: Files
    label: "Input Image Directory"
    description: "Path to the directory of input images"
    file_count: "multiple"
    default: "directory"
    cli_tag: "--dir"
    section_id: "input-args"
    volume_mount: True
    folder_name: "/bilayers/input_images"
    mode: "beginner"
  - name: look_one_level_down
    type: Checkbox
    label: "Look One Level Down"
    description: "look one level down in folder structure for images"
    value: False
    cli_tag: "--look_one_level_down"
    optional: True
    section_id: "input-args"
    mode: "advanced"
```

Here's what I'm saying we should do if the first one say, has no `--flag` but instead is passed positionally, and then the other one it doesn't matter the position . I'll star the changes.

```
  - name: dir
    type: Files
    label: "Input Image Directory"
    description: "Path to the directory of input images"
    file_count: "multiple"
    default: "directory"
    cli_tag: "" <-----diff-----
    cli_order: 0 <-----diff-----
    section_id: "input-args"
    volume_mount: True
    folder_name: "/bilayers/input_images"
    mode: "beginner"
  - name: look_one_level_down
    type: Checkbox
    label: "Look One Level Down"
    description: "look one level down in folder structure for images"
    value: False
    cli_tag: "--look_one_level_down"
    cli_order: False <-----diff-----
    optional: True
    section_id: "input-args"
    mode: "advanced"
```

**Comment by bethac07** [comment]
>Sorry, one more clarification question that we want to save outputs for both the interfaces via given output_dir thing, or this option we are only thinking for jupyter. I believe both, but correct me if I understood otherwise

Definitely you might need these in both interfaces, because you might need to in either case set where the output is going, if you can, and/or find where the output is, if you can't

**Comment by rajavishah** [comment]
> So, to be super clear on the ordering thing: here are two parameters pulled from the current cellpose config:
> 
> ```
>   - name: dir
>     type: Files
>     label: "Input Image Directory"
>     description: "Path to the directory of input images"
>     file_count: "multiple"
>     default: "directory"
>     cli_tag: "--dir"
>     section_id: "input-args"
>     volume_mount: True
>     folder_name: "/bilayers/input_images"
>     mode: "beginner"
>   - name: look_one_level_down
>     type: Checkbox
>     label: "Look One Level Down"
>     description: "look one level down in folder structure for images"
>     value: False
>     cli_tag: "--look_one_level_down"
>     optional: True
>     section_id: "input-args"
>     mode: "advanced"
> ```
> 
> Here's what I'm saying we should do if the first one say, has no `--flag` but instead is passed positionally, and then the other one it doesn't matter the position . I'll star the changes.
> 
> ```
>   - name: dir
>     type: Files
>     label: "Input Image Directory"
>     description: "Path to the directory of input images"
>     file_count: "multiple"
>     default: "directory"
>     cli_tag: "" <-----diff-----
>     cli_order: 0 <-----diff-----
>     section_id: "input-args"
>     volume_mount: True
>     folder_name: "/bilayers/input_images"
>     mode: "beginner"
>   - name: look_one_level_down
>     type: Checkbox
>     label: "Look One Level Down"
>     description: "look one level down in folder structure for images"
>     value: False
>     cli_tag: "--look_one_level_down"
>     cli_order: False <-----diff-----
>     optional: True
>     section_id: "input-args"
>     mode: "advanced"
> ```

Understood, so instead of defining the high-level keyword, we should give the `cli_order` flag to each `parameter`, this would help us tackling the case where some parameters have order matters and rest can be passed at any position

**Comment by bethac07** [comment]
>Understood, so instead of defining the high-level keyword, we should give the cli_order flag to each parameter, this would help us tackling the case where some parameters have order matters and rest can be passed at any position

A nuance - cli_tag and cli_order aren't _necessarily_ mutually exclusive, though in my experience, _often_ if something has to be positioned at the beginning, it may not have a cli flag. But any of the following patterns are possible

`someexecutable --unordered_flag_1 unordered_value_1  --unordered_flag_2 unordered_value_2`
`someexecutable unordered_value_1 unordered_value_2`
`someexecutable ordered_value_1 unordered_value_2`
`someexecutable --ordered_flag_1 ordered_value_1 unordered_value_2`
`someexecutable ordered_value_1 --unordered_flag_2 unordered_value_2`

**Comment by rajavishah** [comment]
> 3. **New Output Directory Flags**: - We gonna introduce two new flags for the `outputs` section: - `output_dir_set` - `output_dir_get` - If `output_dir_set` is an empty string (`""`), it should default to the value provided by `output_dir_get`.


Whilst working on this, I observed a different behavior that all the `generated_files` are saved in `user-given-output-folder` but a `numpy file` (specifically for cellpose `xyz_seg.npy`) is saved in `input-folder`. To display the `outputs` to user, we were only parsing the `user-given-output-folder`. But, we also would have one file generated in `inputs` folder. To resolve this, @gnodar01 and I discussed that this `*.npy` file has no images saved in it [check-cellpose-code](https://github.com/MouseLand/cellpose/blob/0ab64c72e20f5e9f4fe232b929cc9b228c5af358/docs/outputs.rst#L48-L49). So, it would be good idea to just display the `files` from the `user-given-output-folder` and make a point in `Documentation` that if you want to download some files like `*.npy`, then may check `docker-desktop --> Files --> your/input/folder` and download those.

Later, if we feel like there are significant number of Algorithms behaving in a similar way, we could just make a point to traverse both the folders and display all the content

**Comment by bethac07** [comment]
Agreed that that's the right way to go! That should be very outlier-y behavior

**Comment by rajavishah** [comment]
> > Understood, so instead of defining the high-level keyword, we should give the cli_order flag to each parameter, this would help us tackling the case where some parameters have order matters and rest can be passed at any position
> 
> A nuance - cli_tag and cli_order aren't _necessarily_ mutually exclusive, though in my experience, _often_ if something has to be positioned at the beginning, it may not have a cli flag. But any of the following patterns are possible
> 
> `someexecutable --unordered_flag_1 unordered_value_1 --unordered_flag_2 unordered_value_2` `someexecutable unordered_value_1 unordered_value_2` `someexecutable ordered_value_1 unordered_value_2` `someexecutable --ordered_flag_1 ordered_value_1 unordered_value_2` `someexecutable ordered_value_1 --unordered_flag_2 unordered_value_2`

A doubt :
If the `cli_tag` is present at `config.yaml` level, it would always expect us to append it with `someexecutable`? 
Or there could be a case where `cli_tag` is present at `config.yaml` level but algorithm's behavior is to append only the `value` with `someexecutable`?

**Comment by rajavishah** [comment]
This stuff is implemented - hence, closing
